# Config

Sell wand:
  Name: "&6&lSell wand"
  Item: STICK
  Glowing: true
  Lore:
    - "&6Right-Click &eon chest to"
    - "&esell his content!"
    - ""
    - "&eSell wand information:"
    - "&e Multiplier: &6%multiplier%x"
    - "&e Uses: &6%uses%"
  Infinite: "Infinite"


Log sell with sell wand in console: false

# Should we destroy wand when is got 0 use.
Destroy wand: true

Hologram line:
  - "&6Item amount to sell in chest &e%amount% &6items."
  - "&6For a total of &e%price%"

# After how many seconds hologram will be remove
Hologram time: 5