# Config

Sell wand:
  Name: "&6&lSell wand"
  Item: STICK
  Glowing: true
  Lore:
    - "&6Right-Click &eon chest to"
    - "&esell his content!"
    - ""
    - "&eSell wand information:"
    - "&e Multiplier: &6%multiplier%x"
    - "&e Uses: &6%uses%"


Log sell with sell wand in console: false

Item price:
  # You can chose price of item: "ShopGUIPlus", "zShop", "Custom"
  Choice: Custom

  # FORMAT: MATERIALNAME,PRICE Price are per item
  Custom:
    - STONE,1
    - COBBLESTONE,1
    - DIRT,1
    - GOLD_INGOT,1
    - DIAMOND,10

Hologram line:
  - "&6Item amount to sell in chest &e%amount% &6items."
  - "&6For a total of &e%price%"