name: Sellwand
version: ${project.version}
main: me.zachary.sellwand.Sellwand
api-version: 1.16
authors: [ Zach_FR ]
softdepend: [ ShopGUIPlus, HolographicDisplays, zShop, Vault ]
description: Sell wand plugin
